### ISSUE TITLE
Issues compiling for ESP32-C3

### ISSUE THREAD

**Issue by moskakos** [jumakki/esphome-ensto#7] opened 2024-05-16 14:38 UTC
Moi!

I have an ESP32-C3-DevKitC-02 and I have had good luck using `board: esp32-c3-devkitm-1` with some sensors. Unfortunately esphome-ensto doesn't compile using that `board` and spits out some errors. See the log below. Any change ESP32-C3 would be supported?

I also tried `board: esp32doit-devkit-v1` but then the binary won't install.

<details>
<summary>Build log</summary>

```
INFO ESPHome 2024.5.0
INFO Reading configuration /config/esphome/esp32-th.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-th (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Removing unused dependencies...
Library Manager: Removing noise-c @ 0.1.4
INFO Removing noise-c @ 0.1.4
Library Manager: Removing dependencies...
INFO Removing dependencies...
Library Manager: Removing libsodium @ 1.10018.1
INFO Removing libsodium @ 1.10018.1
Library Manager: libsodium@1.10018.1 has been removed!
INFO libsodium@1.10018.1 has been removed!
Library Manager: noise-c@0.1.4 has been removed!
INFO noise-c@0.1.4 has been removed!
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
Compiling .pioenvs/esp32-th/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ble_client/automation.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ble_client/ble_client.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ble_client/sensor/ble_rssi_sensor.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ble_client/sensor/ble_sensor.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/climate/climate.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/climate/climate_mode.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/climate/climate_traits.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32_ble/ble.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32_ble/ble_advertising.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32_ble/ble_uuid.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32_ble_client/ble_characteristic.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32_ble_client/ble_client_base.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32_ble_client/ble_service.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/homeassistant/sensor/homeassistant_sensor.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/template/binary_sensor/template_binary_sensor.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/template/sensor/template_sensor.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/thermostat/thermostat_climate.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/application.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/color.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/component.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/controller.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/log.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/ring_buffer.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/string_ref.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/time.cpp.o
Compiling .pioenvs/esp32-th/src/esphome/core/util.cpp.o
Compiling .pioenvs/esp32-th/src/main.cpp.o
Building .pioenvs/esp32-th/bootloader.bin
Creating esp32c3 image...
Successfully created esp32c3 image.
Generating partitions .pioenvs/esp32-th/partitions.bin
Compiling .pioenvs/esp32-th/lib64d/WiFi/WiFi.cpp.o
Compiling .pioenvs/esp32-th/lib64d/WiFi/WiFiAP.cpp.o
Compiling .pioenvs/esp32-th/lib64d/WiFi/WiFiClient.cpp.o
Compiling .pioenvs/esp32-th/lib64d/WiFi/WiFiGeneric.cpp.o
Compiling .pioenvs/esp32-th/lib64d/WiFi/WiFiMulti.cpp.o
/config/esphome/esp32-th.yaml: In lambda function:
/config/esphome/esp32-th.yaml:705:66: error: no matching function for call to 'min(int32_t&, int)'
                       uint16_t minutes = std::max(0, std::min(length_minutes, 300));
                                                                  ^
In file included from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/deque:60,
                 from src/esphome/components/api/api_frame_helper.h:3,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:195:5: note: candidate: 'template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)'
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
/config/esphome/esp32-th.yaml:705:66: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'int')
                       uint16_t minutes = std::max(0, std::min(length_minutes, 300));
                                                                  ^
In file included from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/deque:60,
                 from src/esphome/components/api/api_frame_helper.h:3,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:243:5: note: candidate: 'template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)'
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
/config/esphome/esp32-th.yaml:705:66: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'int')
                       uint16_t minutes = std::max(0, std::min(length_minutes, 300));
                                                                  ^
In file included from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/algorithm:62,
                 from src/esphome/core/optional.h:19,
                 from src/esphome/components/socket/socket.h:5,
                 from src/esphome/components/api/api_frame_helper.h:14,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3450:5: note: candidate: 'template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)'
     min(initializer_list<_Tp> __l)
     ^~~
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3450:5: note:   template argument deduction/substitution failed:
/config/esphome/esp32-th.yaml:705:66: note:   mismatched types 'std::initializer_list<_Tp>' and 'long int'
                       uint16_t minutes = std::max(0, std::min(length_minutes, 300));
                                                                  ^
In file included from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/algorithm:62,
                 from src/esphome/core/optional.h:19,
                 from src/esphome/components/socket/socket.h:5,
                 from src/esphome/components/api/api_frame_helper.h:14,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3456:5: note: candidate: 'template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)'
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^~~
/data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3456:5: note:   template argument deduction/substitution failed:
/config/esphome/esp32-th.yaml:705:66: note:   mismatched types 'std::initializer_list<_Tp>' and 'long int'
                       uint16_t minutes = std::max(0, std::min(length_minutes, 300));
                                                                  ^
Compiling .pioenvs/esp32-th/lib64d/WiFi/WiFiSTA.cpp.o
Compiling .pioenvs/esp32-th/lib64d/WiFi/WiFiScan.cpp.o
*** [.pioenvs/esp32-th/src/main.cpp.o] Error 1
========================= [FAILED] Took 24.79 seconds =========================
```

</details>

**Comment by jumakki** [comment] 2024-05-16 15:20
Moi, I'm not able to reproduce the issue, but log indicates that it could be fixed by explicitly specifying type to std::min() function.
Can you try to add <int32_t> after std::min?
So replace
`uint16_t minutes = std::max(0, std::min(length_minutes, 300));`
on line 705 with
`uint16_t minutes = std::max(0, std::min<int32_t>(length_minutes, 300));`

**Comment by jumakki** [comment] 2024-05-16 16:29
You are right, my compilation with that board fails also.
Changing line to this will fix it. I'll update the code in repository accordingly
`uint16_t minutes = std::max<int>(0, std::min<int>(length_minutes, 300));`

**Closed as completed** 2024-05-16 16:58 UTC
